### ISSUE TITLE
Building a singleton P2P network for syncing Scuttlebutts?

### ISSUE THREAD

**Issue by paulkernfeld** [dominictarr/scuttlebutt#48]
I am interested in building a singleton (e.g. Bitcoin, BitTorrent) P2P network that allows Scuttlebutts from different computers to be easily connected. This is in contrast to [scuttlebot](https://github.com/ssbc/scuttlebot), which provides a very decentralized network that is explicitly designed _not_ to be a singleton.

In order to build this network, a transport layer is necessary. BitTorrent seems like a good candidate for this because it's flexible, well-supported, already established, and takes care of some pesky details like NAT. If there's already something that does this, though, I would be happy to use that instead!

My idea is to build a BitTorrent extension that facilitates Scuttlebutt exchange between two nodes. [bittorrent-protocol](https://github.com/feross/bittorrent-protocol) has an [extension API](https://github.com/feross/bittorrent-protocol#extension-api) that I believe could be used for this.

I am curious if anyone has ideas about better ways to implement this singleton P2P network

**Comment by dominictarr** [comment]
what sort of application do you want to build upon this? Can you paint me a bit of a picture of that so I can better understand what you are envisioning?

**Comment by paulkernfeld** [comment]
Yeah... this is too vague a description. I'll close this and open another issue with a better description.
