### ISSUE TITLE
Data sync issue 

### ISSUE THREAD

**Issue by vinayk047** [dominictarr/scuttlebutt#51]
I've following network setup

![screen shot 2018-01-24 at 3 57 18 pm](https://user-images.githubusercontent.com/11410214/35327311-50fc7146-011f-11e8-8e38-9e7d74b42515.png)

**1**. If i update model A & E at same time than only changes of model A are propagated in network
check following image

![screen shot 2018-01-24 at 4 01 16 pm](https://user-images.githubusercontent.com/11410214/35327733-636affe0-0120-11e8-84f1-1c89cf81a3a2.png)

**2.** If u update model E after few seconds than the changes are propagated in network; check following image.

![screen shot 2018-01-24 at 4 03 41 pm](https://user-images.githubusercontent.com/11410214/35327802-98575208-0120-11e8-901c-b0efd6ce1288.png)

is this normal behaviour or a bug?

**Comment by dominictarr** [comment]
yes this is correct behaviour

**Comment by dominictarr** [comment]
oh sorry, you are connecting these streams wrong!

you cannot pipe as to bs AND pipe cs to bs. you should use each stream only once!
bs should actually be bs1 bs2 bs3
``` js
as = a.createStream()
bs1 = b.createStream()
bs2 = b.createStream()
cs = c.createStream()
as.pipe(bs1).pipe(as)
cs.pipe(bs2).pipe(cs)
//etc...
```

**Comment by vinayk047** [comment]
@dominictarr, Ahh ok.
thank you for the answer and a awesome module.
